name: 

on:
  workflow_dispatch:

jobs:
  buat-commit-mundur:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Tarik Kode
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Proses Looping Commit Masa Lalu
        run: |
          # WAJIB UBAH BARIS DI BAWAH INI DENGAN DATA ASLIMU
          git config --global user.email "radittantra36@gmail.com"
          git config --global user.name "radityaarinanta"
          
          DAYS_BACK=30
          
          for i in $(seq $DAYS_BACK -1 1); do
            PAST_DATE=$(date -d "$i days ago" -u +'%Y-%m-%dT%H:%M:%SZ')
            
            # Mengubah file biasa bernama riwayat.txt
            echo "Menambahkan kontribusi untuk tanggal: $PAST_DATE" >> riwayat.txt
            git add riwayat.txt
            
            # Melakukan commit mundur
            GIT_AUTHOR_DATE="$PAST_DATE" GIT_COMMITTER_DATE="$PAST_DATE" git commit -m "Commit masa lalu: $PAST_DATE"
          done
          
          # Dorong ke repositori
          git push
